Big homework 20
NET16-Homeworks/BigHomework_1 pull request #1
Opened 2022-09-28 14:09 UTC by BFipe

При оформлении нашего кредита коллекторы в подарок

2022-10-03 16:34 UTC, im-kborovik requested changes

2022-10-03 16:34 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            bool isTaskCompletedSucess = false;
Сделай плз без этой переменной. Очень тяжело читать код, потому что ты пытаешь дать юзеру шанс ввести значение правильно. Это благое намерение, но из-за этого код стал сложночитаемым.

2022-10-03 16:34 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Program.cs
> +while (true)
Не вижу как будет заканчиваться этот бесконечный цикл.

2022-10-03 16:34 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/User/User.cs
> +        private static UserService userService = new UserService();
Сразу нет. Сущности не должны содержать бизнес-логики. Это грубейшее нарушение ООП и антипаттерн.

2022-10-03 16:34 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/User/UserService.cs
> +            bool isTaskCompletedSucess = false;
То же самое. Непонятно чего ты пытаешься этим добиться

2022-10-03 16:37 UTC, BFipe commented on BigHomework_1/BigHomework_1/Program.cs
> +while (true)
в case 6 есть return, он выводит из цикла и завершает программу

2022-10-09 09:16 UTC, im-kborovik requested changes

2022-10-09 09:16 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            }
очень странно получается, что у тебя сначала проверяется есть ли юзер с таким email, а только потом проверяется, а не пустой ли email. выглядит нелогично.

2022-10-09 09:16 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            }
а где проверка, что юзер ввёл правильный рэйт из списка?

2022-10-09 09:16 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/User/UserService.cs
> +
удаляй пожалуйста ненужные пустые ненужные пробельные строки. выглядит, как будто ты забыл что-то написать.

2022-10-09 12:47 UTC, BFipe commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            }
!avaliableRates.Contains(loanRate)

2022-10-16 12:02 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            }
.... радели эти условия, нифига непонятно

2022-10-16 12:04 UTC, im-kborovik approved these changes

2022-10-16 12:04 UTC, closed without merging