done
NET16-Homeworks/BigHomework_1 pull request #3
Opened 2022-10-02 12:29 UTC by Sokaster

Не разобрался до конца как работает формула из документа, ибо раньше видел другие и попробовал считать с ними, результаты вышли другие) А так спасибо за задание. Жду замечания

2022-10-09 09:58 UTC, im-kborovik requested changes

2022-10-09 09:58 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanCalculator.cs
> +
я ужасно не люблю, когда так делают :) эти пробелы бесполезны, удали плз.

2022-10-09 09:58 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanCalculator.cs
> +                ostatokSummOfCredit = Math.Round(ostatokSummOfCredit - everyMonthlyPayingAmount + (ostatokSummOfCredit * creditPercents / 100 / 12), 3);
`creditPercents / 100 / 12` - у тебя уже это значение в percentageStavka, зачем опять его высчитывать?

2022-10-09 09:58 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            bool isOkay = false;
Насколько я понял, ты пытался сделать с помощью этой переменной модульный подход к опросу данных пользователя, но это слишком усложнило код, он стал почти нечитаемым. Лучше заставить пользователя начать весь процесс заново, выбросив на каком-то из этапов исключение, потому что код не должен писаться в угоду удобства пользования UI.
Удали плз эту переменную и проверки, которые связаны с ней, и напиши более прямолинейный код.

2022-10-09 09:58 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +                List<double> Rates = new List<double>() { 5, 7.2, 10.2, 15.4};
вынеси это в приватное статическое поле, потому что мы не планируем изменять список в процессе выполнения программы.

2022-10-09 09:58 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Program.cs
> +
Добавь сюда вопрос хочет ли юзер продолжить работать с программой. Если нет, то нужно закончить бесконечный цикл.

2022-10-09 09:58 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/User/User.cs
> +        private static UserService userService = new UserService();
Никогда не используй классы с бизнес логикой внутри классов-сущностей: они должны хранить в себе только данные и ничего больше. Саму проверку на существование сущности нужно вынести в сервис.

2022-10-16 16:11 UTC, Sokaster commented on BigHomework_1/BigHomework_1/Loan/LoanCalculator.cs
> +
deleted

2022-10-16 16:12 UTC, Sokaster commented on BigHomework_1/BigHomework_1/Loan/LoanCalculator.cs
> +                ostatokSummOfCredit = Math.Round(ostatokSummOfCredit - everyMonthlyPayingAmount + (ostatokSummOfCredit * creditPercents / 100 / 12), 3);
deleted.

2022-10-16 16:14 UTC, Sokaster commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +                List<double> Rates = new List<double>() { 5, 7.2, 10.2, 15.4};
вынес

2022-10-16 17:35 UTC, Sokaster commented on BigHomework_1/BigHomework_1/User/User.cs
> +        private static UserService userService = new UserService();
Понял, спасибо, беру на заметку)

2022-10-16 17:36 UTC, Sokaster commented on BigHomework_1/BigHomework_1/Loan/LoanManager.cs
> +            bool isOkay = false;
Убрал

2022-10-23 10:45 UTC, closed without merging