Loan application has been completed
NET16-Homeworks/BigHomework_1 pull request #5
Opened 2022-10-07 14:40 UTC by kricobelka

должно все работать
еще буду апргрейдить

2022-10-10 06:00 UTC, kricobelka commented
подправила сегодня

2022-10-16 12:45 UTC, im-kborovik requested changes

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Classes/User.cs
> +    public static class Validator
Вынеси в отдельный файл

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +    internal class UserServ
Почему ты не можешь назвать класс UserService? Какой смысл в сокращении названия класса? Поверь компилятору глубоко пофиг, как ты его назовёшь, он всё равно его переназовёт по-своему.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +        double[] _loanRate = new double[] { 10, 11.5, 13.4 };
Модификаторы доступа где?

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +                if (loanrate == _loanRate[0] || loanrate == _loanRate[1] || loanrate == _loanRate[2])
Так стоп... А что ты будешь делать если количество рэйтов увеличится?))
Так не пойдёт. У нас есть метод Contains, используй его. С ним можно и без цикла обойтись.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +                    throw new Exception("There is no such loan rate. Please use the existing one");
ObjectNotFound?

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loans/Loan.cs
> +        private static UserServ userService = new UserServ();
Классы-сущности не должны знать о классах бизнесс логики.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loans/Loan.cs
> +            }
Убери эту проверку. Вместо этого создай такую же в LoanManager, когда спрашиваешь email.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Loans/LoanCalculator.cs
> +            Console.WriteLine(balanceNextPeriod);
Выведи для каждого месяца.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Program.cs
> +while (menu != 5)
Всё ещё бесконечный цикл, который никак не прервать. 
Добавь плз в конце выпонения цикла, хочет ли юзер закончить работу.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Program.cs
> +    }
Оберни в try-catch и обработай все наши кастомные ошибки. Просто выводи сообщение из исключения.

2022-10-16 12:45 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +            string email = Console.ReadLine();
Проверка на уникальность email?

2022-10-18 19:15 UTC, kricobelka commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +    internal class UserServ
потому что у меня папка в которой лежит файл также называетс UserService
и поэтому когда я пытаюсь обратиться к классу (который тоже назыв-ся UserService), оно думает, что  я обращаюсь к namespace

2022-10-18 19:16 UTC, kricobelka commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +    internal class UserServ
@im-kborovik

2022-10-18 19:16 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Classes/User.cs
> +    public static class Validator
done

2022-10-18 19:17 UTC, kricobelka commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +        double[] _loanRate = new double[] { 10, 11.5, 13.4 };
подожди, а это тогда  что? @im-kborovik 
 **private** static Dictionary<string, List<Loan>> _userLoans =

2022-10-18 19:27 UTC, kricobelka commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +                    throw new Exception("There is no such loan rate. Please use the existing one");
да, можно  заменить на ObjectNotFoundException
но у меня ObjectNotFoundException выводит след сообщение: The object wasn’t found
я указала Exception, чтобы самой ввести желаемый текст)

Если юзать Objectnotfoundexception, как его правильнее переопределить, чтобы выводило "There is no such loan rate. Please use the existing one" именно для этого конкретного случая?
 @im-kborovik

2022-10-18 19:46 UTC, kricobelka commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +                if (loanrate == _loanRate[0] || loanrate == _loanRate[1] || loanrate == _loanRate[2])
done

2022-10-18 19:54 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Loans/Loan.cs
> +            }
fixed

2022-10-18 20:02 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Loans/LoanCalculator.cs
> +            Console.WriteLine(balanceNextPeriod);
на этом мои познания в математике заканчиваются)

2022-10-18 20:29 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Program.cs
> +while (menu != 5)
у меня в менюшке есть case 5 - выйти из приложения
он выйдет из прилаги когда юзер нажмет 5, 
в чем проблем?
или ты хотел бы, чтоб я по-другому как-то сделала?

@im-kborovik

2022-10-18 20:41 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Loans/Loan.cs
> +        private static UserServ userService = new UserServ();
fixed

2022-10-18 20:43 UTC, kricobelka commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +            string email = Console.ReadLine();
или ты хочешь чтоб я использовала ObjectExistsException ?

2022-10-20 18:10 UTC, kricobelka commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +                    throw new Exception("There is no such loan rate. Please use the existing one");
resolved

2022-10-20 18:55 UTC, kricobelka commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +            string email = Console.ReadLine();
fixed

2022-10-20 19:15 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Program.cs
> +    }
fixed

2022-10-23 10:37 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +    internal class UserServ
назови фолдер Srvices. у нас не тенденции под каждый сервис создавать отдельную директорию

2022-10-23 10:38 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +        double[] _loanRate = new double[] { 10, 11.5, 13.4 };
один из четырёх. а остальные где?

2022-10-23 10:41 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Program.cs
> +while (menu != 5)
он прервёт выполнение свича, а не цикла. у тебя же в остальных секция тоже есть break, ты думаешь они по-другому работают?)

2022-10-31 05:21 UTC, kricobelka commented on BigHomework_1/BigHomework_1/UserService/UserServ.cs
> +    internal class UserServ
done

2022-10-31 05:21 UTC, kricobelka commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +        double[] _loanRate = new double[] { 10, 11.5, 13.4 };
static есть еще)

2022-10-31 05:34 UTC, kricobelka commented on BigHomework_1/BigHomework_1/LoanService/LoanManager.cs
> +        double[] _loanRate = new double[] { 10, 11.5, 13.4 };
fixed
налепила модификаторов)

2022-10-31 05:43 UTC, kricobelka commented on BigHomework_1/BigHomework_1/Program.cs
> +while (menu != 5)
так выполнения и свича, и  цикла прервется, когда я нажму 5

2022-11-06 19:57 UTC, im-kborovik commented on BigHomework_1/BigHomework_1/Program.cs
> +while (menu != 5)
ах, лол, верно. чёт я туплю

2022-11-06 19:57 UTC, im-kborovik approved these changes

2022-11-06 19:57 UTC, closed without merging